[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_URL = "http://qxw.2ee.mytemp.website/projectipt2/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200